### PR TITLE
Optimize the png files

### PR DESCRIPTION
**Pull request by xfq**

### CODE REVIEW

**Comment by r12a** [comment]
How did you get these reductions?  (I had already reduced using ImageOptim)  Are they still visually identical?

**Comment by xfq** [comment]
I used [TinyPNG](https://tinypng.com/). I have compared both locally and [online](https://github.com/w3c/i18n-drafts/pull/393/files) and can't see a significant difference.

**Comment by r12a** [comment]
Ok. Let's merge it. I'm a little suspicious (particularly of the arabic text image) because i already optimised them and got nowhere near that kind of compression. So i'll duplicate my local files and do a comparison after the merge.

**Comment by himorin** [comment]
Looking into color palette, nearby and rarely used colors are summarized into one, like three gray colors from `#656565` to `#676767` into `#666666` (which appears at edge of glyph by antialiasing).

**Comment by r12a** [comment]
Thanks @himorin.  I compared the before and after versions, and can't see any difference.

**Pull request merged**
