### PR TITLE
Japanese translation for “Declaring character encodings in HTML”

### PR DESCRIPTION
**Pull request by hail2u**
Just a personal demand, I’ve translated this useful document.

### CODE REVIEW

**Comment by r12a** [comment]
@hail2u thanks for submitting this translation!  Before merging, i have two requests:
1. please confirm for me that you have read https://www.w3.org/International/2004/06/translation.en.html and agree with the instructions.
2. we still need translations for some of the japanese boilerplate text used for these pages (because we recently updated the template).  Could you please also provide an updated version of the boilerplate-ja.js file found at https://github.com/w3c/i18n-drafts/blob/gh-pages/javascript/boilerplate-text/boilerplate-ja.js ?  Basically, all the outstanding english text string values need to be translated to Japanese. Where a message has been changed, rather than being new, you can see the previous translations at https://github.com/w3c/i18n-drafts/commit/3f4552f747aed6edb84be2b530a701eadd35ab1f in case that helps.

**Comment by r12a** [comment]
oh, one other thing: we need to put back the names of the contributors in 

```
f.contributors = 'Henri Sivonen, Gunnar Bittersmann'; // people providing useful contributions or feedback during review or at other times
```

**Comment by hail2u** [comment]
I have already read “Translation instructions” and “Translator's checklist”. Also `f.contributors` value was reverted (I misunderstood about this value).

For `boilerplate-ja.js` translation, should I create another pull request?

**Comment by r12a** [comment]
> I have already read “Translation instructions” and “Translator's checklist”. Also f.contributors value was reverted (I misunderstood about this value).

great. Thanks.

> For boilerplate-ja.js translation, should I create another pull request?

whatever you prefer. Add it to this one or create another. I won't publish the translation until i get all together.

**Comment by hail2u** [comment]
Updated boilerplate in this pull request!

**Comment by r12a** [comment]
Excellent. I'll merge tomorrow, since it's late here and i want to check my repo is in order first.

**Comment by r12a** [comment]
Ok, all done and published.  Thanks again!

**Pull request merged**
