### PR TITLE
Created tutorial-char-enc/index.fr.html

### PR DESCRIPTION
**Pull request by brandelune**

### CODE REVIEW

**Comment by r12a** [comment]
LGTM, thanks!

Should i publish+announce it now, or should we batch it up with one or more upcoming translations?

**Comment by brandelune** [comment]
Just do as you wish, no rush here.

**Comment by brandelune** [comment]
Just in case you forgot, the article is still not published. I had forgotten that you had delayed publication and was confused this morning when I saw the site did not have the FR version... :)

**Comment by r12a** [comment]
I've been waiting for more to come in, so that i can announce them all together (see that the status is 'Received' at https://github.com/w3c/i18n-drafts/projects/2, rather than 'Published').  But maybe i should just publish, to avoid confusion.

**Comment by r12a** [comment]
It's now published. Thanks.

**Pull request merged**
