### PR TITLE
Update boilerplate-ar.js

### PR DESCRIPTION
**Pull request by ntounsi**
Arabic translation done. Needed preview to fix bidi stuffs.

### CODE REVIEW

**Comment by r12a** [comment]
Thanks very much, Najib!

**Comment by r12a** [comment]
Ah, i just spotted one that you missed:

s.followOurNews = "Follow our news feed."

Could you provide the string here (rather than create a new PR), and i'll insert it.

Also, would you be able to translate the small amount of text in https://github.com/w3c/i18n-drafts/blob/gh-pages/article-list/articlelist.ar.html ?

**Comment by ntounsi** [comment]
On 7/25/19 11:53, r12a wrote:

> Ah, i just spotted one that you missed:
>
> s.followOurNews = "Follow our news feed."
>
> Could you provide the string here (rather than create a new PR), and 
> i'll insert it.
>
تابع موجز أخبارنا

meaning : "Follow our news summary". Another translation would be:

تابع مجرى أخبارنا

which means : "Follow our news stream".


> Also, would you be able to translate the small amount of text in 
> https://github.com/w3c/i18n-drafts/blob/gh-pages/article-list/articlelist.ar.html 
> ?
>
Yes.

**Comment by r12a** [comment]
Done. Thanks.

**Pull request merged**
