### PR TITLE
Update qa-html-di

### PR DESCRIPTION
**Pull request by vinhill**
I tested [changing an elements directionality](https://www.w3.org/International/questions/qa-html-dir#userexplicit) with the latest firefox release and the keyboard-shortcut does update the value of the elements `dir` attribute.

### CODE REVIEW

**Comment by r12a** [comment]
@vinhill thanks for this correction.  Looking in the inspector, i agree that the direction is now set by the keypress.

However, i'm not seeing Firefox picking up the direction in dirname  so i think it would be worth me adding a note to that effect (as well as removing info about Internet Explorer).  Do you see the same (see https://www.w3.org/International/i18n-tests/results/the-dirname-attribute)?

**Comment by vinhill** [comment]
Yes, dirname is not implemented in Firefox ([Bugzilla entry](https://bugzilla.mozilla.org/show_bug.cgi?id=675943)). Though we are currently working on fixing this.

**Comment by r12a** [comment]
@vinhill It sounds like you're working on fixing dirname in the near term. If so, i guess it's not worth adding a note. Do you expect dirname to be supported in a few months from now?

**Comment by vinhill** [comment]
@r12a I do hope so and can notify you otherwise.

**Comment by r12a** [comment]
@vinhill thanks again for proposing this PR.  In the end, i had other edits to make to that article so i made the changes myself rather than pulling this in.

**Pull request closed without merging**
