### PR TITLE
QA Native Direction (edits)

### PR DESCRIPTION
**Pull request by aphillips**
- Merged "summary" with intro
- Added language to the metadata discussed
- Added a link to the glossary for "string direction"
- Added a link to the i18n-drafts repo

[Preview](https://deploy-preview-591--i18n-drafts.netlify.app/questions/qa-direction-native.html)

### CODE REVIEW

**Comment by aphillips** [comment]
Argh. I forgot that I had the language negotiation article in my gh-pages branch when I re-branched this article. Ignore the first file and concentrate on the qa-direction-native.html file for comments.

**Comment by xfq** [comment]
It seems that there is still no APIs related to language metadata mentioned in the article?

**Comment by r12a** [comment]
typo: framworks

don't forget to update the publication dates

otherwise, ok.  It would be nice to have an example of what can be done, but that's probably too complicated.

**Comment by aphillips** [comment]
@r12a Thanks for the typo and nudges about the dates. I also added an example (check it out)

**Comment by r12a** [comment]
Aha.  Good.  But the formatting of the blocks needs some attention in the preview.  Does it look better in real life?

**Comment by aphillips** [comment]
> Does it look better in real life?

No. I was hoping it looked better on github or in production, but I think it's a gap in our QA stylesheet.

**Pull request merged**
