### PR TITLE
Update boilerplate text of ko-kr

### PR DESCRIPTION
**Pull request by techhtml**
#208

### CODE REVIEW

**Comment by r12a** [comment]
Many thanks @techhtml !

**Comment by r12a** [comment]
@techhtml there are a few more strings in the document that need translation, and also the page at https://www.w3.org/International/articlelist.ko (basically just intro and headings).  Please let me know if you are interested in translating those too.  (the latter file isn't on github, so i'll need to send you a file.)

**Comment by techhtml** [comment]
@r12a Sounds Great! I will ping you when I find some interested docs.

**Comment by r12a** [comment]
Sorry for not being clear, @techhtml, but i meant that we need [1] some more strings translated in the file https://github.com/w3c/i18n-drafts/blob/gh-pages/javascript/boilerplate-text/boilerplate-ko.js (especially near the bottom), and [2] the actual page at https://www.w3.org/International/articlelist.ko

Of course, it would be great to also get translations of the articles listed on that page too, but our immediate need is to address the shortfall for the boilerplate text.  Hope that's clearer.

**Comment by techhtml** [comment]
@r12a a-ha, Sorry for my misunderstand haha.
I will translate this docs Korean and will open PR soon.

**Pull request merged**
