### PR TITLE
Spanish Translations & PNG images

### PR DESCRIPTION
**Pull request by cmatmar1**
Hello Richard,

Please find attached the Spanish translation for the article Time & date: Essential concepts.

Please do not hesitate to contact me for any further modifications or explanations that you may need.

Kind regards,

Carlos

### CODE REVIEW

**Comment by cmatmar1** [comment]
Dear Richard,

You will find all the new files ready for revision, including two PNG images that I translated for the article Personal names around the world. My apologies for the messy pull request.

I look forward to hearing from you soon.

Kind regards,

Carlos

**Comment by r12a** [comment]
hello Carlos. This PR shouldn't include any of the existing english files, so it seems rather suspicious and i won't merge it.

Instead, i have taken the spanish text and manually created new files.

You can see the result for the first file at http://w3c.github.io/i18n-drafts/articles/definitions-time/index.es.html

I had to make a number of edits to the source text, over and above those related to the validation warnings you received.  You can see them in the following commits:
https://github.com/w3c/i18n-drafts/commit/d5b30c969b8eab9617cbc7882be4a97601576800
https://github.com/w3c/i18n-drafts/commit/095a5c5ce4d20fcd07933dab8fbb5eb6972677c5

I'll now start on the second translation.

**Comment by r12a** [comment]
You can see the second file at http://w3c.github.io/i18n-drafts/questions/qa-personal-names.es.html

Fixes made can be viewed at 
https://github.com/w3c/i18n-drafts/commit/2c25521d2c5fddf8145194f2a6dba86ff670b782
https://github.com/w3c/i18n-drafts/commit/3b0c45dc796bf5d3503bd43f375d3edc261ca0ab

Please take a look at the rendered files, and let me know if you are happy to proceed, at which point i'll publish to the main site. Thanks.

**Comment by brandelune** [comment]
Maybe this PR can be closed now ?

**Comment by cmatmar1** [comment]
Hi Jean,

Is it possible to get some more time so I can go through it and correct
some mistakes? I have been waiting for the final presentation of this
project to send you the final OK.

Many thanks in advance.

I look forward to receiving your reply.

Kind regards,

**Comment by brandelune** [comment]
I'm certainly not the one who decides. Just do as you can.

**Comment by r12a** [comment]
@cmatmar1, I think it does probably make sense to close this pull request, given that it produces many conflicts now, and the content has been replaced by the commits mentioned above.  Your translations are still not published on the main site, pending the final checks you mention above.  In the meantime, they are available, however, at the following locations. 

http://w3c.github.io/i18n-drafts/articles/definitions-time/index.es.html

http://w3c.github.io/i18n-drafts/questions/qa-personal-names.es.html

 I suggest that when you have done the final review you raise issues or a pull request against these documents.  I will only complete the publication process after i hear from you.

**Pull request closed without merging**
