### PR TITLE
Update the group page

### PR DESCRIPTION
**Pull request by xfq**
Changes:

* Sort the repos in "Internationalization Working Group" alphabetically
* Remove mlreq from "Internationalization Working Group", since it's mentioned in "Mongolian Layout Task Force"
* Add i18n-glossary, i18n-issues, i18n-request, i18n-tests, localizable-manifests, ruby-t2s-req, and simple-ruby repos
* http -> https

### CODE REVIEW

**Comment by xfq** [comment]
Please don't merge for now. I have some further changes.

**Comment by xfq** [comment]
I didn't add the interactive test repos (like https://github.com/w3c/text_direction_tests). Should I add them?

**Comment by r12a** [comment]
It's great that you ordered the GH repos for the i18n WG alphabetically.  I wanted that to happen.

For the /about page, however, here are a few other things i think we could do to improve the page:
1. separate the GH repos in the WG list with • rather than a comma - i think it will make it easier to read.
2. follow the WG layout for the task forces: now that we have a home page that is not just the repo page, i suggest that we
    1. add a line for each with a link to 'Home page', 
    2. add another line immediately after that links to 'Discussion threads'
    3. in the line that starts with 'Github (w3c/afrlreq)', replace it with 'Github: <w3c/afrlreq>' (where the angle brackets indicate links).  Do the same for all the task forces.
3. move the w3c/ruby-t2s-req link so that the jlreq task force has Github: w3c/jlreq • w3c/simple-ruby • w3c/ruby-t2s-req

**Comment by r12a** [comment]
You should probably also add yourself to the list of contacts.

**Comment by r12a** [comment]
> I didn't add the interactive test repos (like https://github.com/w3c/text_direction_tests). Should I add them?

Yes, i think that would be useful.  Add them under the WG list, i guess.

**Comment by r12a** [comment]
On second thoughts, maybe add the interactive test repos and w3c/klreq to the IG section?

**Comment by xfq** [comment]
Thanks. PR updated.

**Comment by r12a** [comment]
> in the line that starts with 'Github (w3c/afrlreq)', replace it with 'Github: <w3c/afrlreq>' (where the angle brackets indicate links). Do the same for all the task forces.

I didn't actually mean you to include the < > in the page, sorry - that was just an indication that the text was a link. I was going to say don't worry about it, but it makes it harder to read the jlreq line, where there are multiple links, so maybe remove those.

Otherwise, looks good, thanks.

**Comment by xfq** [comment]
Should be fixed now.

**Review by r12a — APPROVED** [review]

**Comment by xfq** [comment]
Thank you!

**Pull request merged**
