### PR TITLE
Fix some typos and change some phrases questions/qa-i18n.ru (for #245 and #246)

### PR DESCRIPTION
**Pull request by corocoto**
For #245 and #246

- Fixing some typos like extra quotes; 
- Changing some phrases on russian;
- Translation some non-translated english words on russian.

### CODE REVIEW

**Comment by r12a** [comment]
Many thanks for this @CreativeRusBear.  Before i merge it, do you want me to acknowledge your contribution.  For example, we could add your name to 
```
f.contributors = '' // people providing useful contributions or feedback during review or at other times
```
Perhaps something like: 
```
f.contributors = 'Artem Gusev made modifications to the translation.' // people providing useful contributions or feedback during review or at other times
```
but in Russian, of course.

**Comment by corocoto** [comment]
@r12a Yes, it would be great! Thanks

Do I need to correct these lines on the file? Or will you do this?

**Comment by r12a** [comment]
Could you add it to this pull request?  (Also because my russian is now extinct.)

**Comment by corocoto** [comment]
Yes, sure

**Comment by corocoto** [comment]
@r12a Done.

**Comment by r12a** [comment]
Спасибо Артем!

**Pull request merged**
