### PR TITLE
Translate the Getting Started page into Chinese

### PR DESCRIPTION
**Pull request by xfq**
I also fixed some typos in the English version.

### CODE REVIEW

**Comment by r12a** [comment]
@xfq I see that this is marked for requesting review, but i also see that you didn't translate the descriptions just below the links.  Is the review phase premature, or were you intending not to translate those sentences?

**Comment by xfq** [comment]
I wrote "titles in English mean that the article does not have a Simplified Chinese version" (in Chinese) at the top. Since a Chinese translator is translating a lot of the articles mentioned on this page, we will hopefully have more Chinese content on this page soon.

The reason I didn't translate the titles is that I want the titles here to be the same as the translated titles, and the reason I didn't translate the descriptions below the titles is that many of the descriptions come from the article, and I want the descriptions to be the same as the descriptions in the (translated) article.

**Comment by r12a** [comment]
Ok for the titles.  I just thought that the descriptions are useful to translate to give a Chinese reader an idea of what the link is about.  It's up to you.  Let me know.

**Comment by xfq** [comment]
OK. I have translated the descriptions.

**Pull request merged**
