### PR TITLE
Translate Monolingual vs. multilingual Web sites into zh-hans

### PR DESCRIPTION
**Pull request by cuihuan**
old PR:https://github.com/w3c/i18n-drafts/pull/359

### CODE REVIEW

**Comment by cuihuan** [comment]
@xfq 之前提交的分支，在刷新代码的时候，log异常了，已经重新fork，变更提交了

**Review by xfq — APPROVED** [review]

**Comment by r12a** [comment]
@xfq You may have noticed that i've been working through all articles and their translations, applying the new 2022 template and fixing up various items along the way.  I hope to finish by tomorrow.  I think it would make sense to delay any merging of PRs until that is complete.

**Comment by xfq** [comment]
@cuihuan I see you are translating a new article in this PR.

Would you please do it in a new branch/PR? Thank you!

**Comment by cuihuan** [comment]
@xfq done, The temporary content has been rolled back.
 very sorry, temporary translations have been switched to a new branch

**Comment by r12a** [comment]
@cuihuan Thanks for this translation. Over the past few days we've been updating the template used for articles. So, rather than merging this PR as is, i took a copy of the source text and updated it to the new template, then manually uploaded it.  I'll therefore just close this PR, but your edits are now published.

**Pull request closed without merging**
