### PR TITLE
qa-html-language-declarations French version

### PR DESCRIPTION
**Pull request by notabene**
This needs a review by a French-speaking person.

### CODE REVIEW

**Comment by r12a** [comment]
Thanks Stephane, but there's a paragraph missing at the start of the Quick Answer section.  Could you provide that?

**Comment by r12a** [comment]
oh, btw, fwiw, you missed to convert

> ../javascript/boilerplate-text/boilerplate-en.js

to 

> ../javascript/boilerplate-text/boilerplate-fr.js

that's what turns all the boilerplate text into french.

**Comment by notabene** [comment]
Sorry about the forgotten paragraph, I'll do it ASAP.

Same with the boilerplate.

Stay tuned :)

**Comment by notabene** [comment]
I hope it's OK now, sorry for forgetting!

**Comment by r12a** [comment]
@notabene many thanks!  Now live.
https://www.w3.org/International/questions/qa-html-language-declarations.fr

**Pull request merged**
